version: '3.3'

services:
  db_application_system:
    image: public.ecr.aws/bitnami/postgresql:11.12.0
    container_name: db_application_system
    networks:
      - local
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=dev_db
      - POSTGRES_PASSWORD=dev_db
    ports:
      - 5432:5432

  redis_cluster:
    container_name: redis_cluster
    image: grokzen/redis-cluster:5.0.6
    networks:
      - local
    privileged: true
    sysctls:
      net.core.somaxconn: '511'
    environment:
      - IP=0.0.0.0
    ports:
      - '7000-7005:7000-7005'

networks:
  local:
