version: '3.3'

services:
  db_endorsements:
    image: public.ecr.aws/bitnami/postgresql:11.12.0
    container_name: db_endorsements
    networks:
      - local
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=dev_db
      - POSTGRES_PASSWORD=dev_db
    ports:
      - 5432:5432

networks:
  local:
