version: '3.3'

services:
  db_services_auth_api:
    image: public.ecr.aws/bitnami/postgresql:11.12.0
    container_name: db_services_auth_api
    networks:
      - local
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=dev_db
      - POSTGRES_PASSWORD=dev_db
    ports:
      - 5433:5432

networks:
  local:
